server:
  port: 8085

spring:
  application:
    name: merchant-service



  datasource:
#    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fisheriz_db?useSSL=false
    username: root
    password:

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:


        dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: create

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true


