spring:
  application.name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


server:
  port: 8765

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
