spring:
  application:
    name: eureka-server
#configuration for Spring Boot Admin Client
  boot:
    admin:
      client:
        url: http://localhost:9000/

#configuration for Actuator (Spring Boot Admin require this)
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: ALWAYS

server:
  port: 8761

#configuration for Eureka server
eureka:
  client:
    register-with-eureka: false



