
spring:
  application:
    name: customer-service
    spring:
      cloud:
        config:
          enabled: true
          uri: http://localhost:8888


server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/



management:
  endpoints:
    jackson:
      isolated-object-mapper: false




