server:
  port: 8888
spring:
  application:
    name: fisheriz-config-server
#  profiles:
#    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/technoavi/fisheriz-config/
          clone-on-start: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/




