spring:
  application:
    name: circuit-breaker-1

#Actuator configuration
management:
  endpoints.web.exposure.include:
    - '*'
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

#Circuit-breaker configuration
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      fishermanCircuitBreaker:
        registerHealthIndicator: true
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        automaticTransitionFromOpenToHalfOpenEnabled: true
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60
        eventConsumerBufferSize: 10
