spring:
  application:
    name: fisherman-service
  datasource:
    url: jdbc:mysql://localhost:3306/fiseherman_db?createDatabaseIfNotExist=true
    username: root
    password: Naren@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
