spring:
  application:
    name: api-gateway

#configuratin for API-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 8086

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/